---
- hosts: cm
  remote_user: root
  vars_files:
    - external_vars.yml

  tasks:
  - name: Install packages needed
    package:
      name: '{{ item  }}'
      state: present
    with_items:
      - krb5-server
      - krb5-workstation
      - krb5-libs
      - openldap-clients
  
  - name: write the krb5 config file
    template:
      src: templates/krb5.conf.j2
      dest: /etc/krb5.conf

  - name: Check if DB already exists
    stat:
      path: /var/kerberos/krb5kdc/principal
    register: db_exists
  
  - name: Destroy Existing KDC Database
    command: /bin/bash -c "kdb5_util destroy -f {{ REALM }}"
    when: db_exists.stat.exists == true
    
  - name: configure kadmin
    command: /bin/bash -c "kdb5_util create -s -P {{ adm_var.password }}"

  - name: Start and Enable Kerberos
    service:
      name: '{{ item }}'
      state: reloaded
      enabled: yes
    with_items:
      - krb5kdc
      - kadmin

  - name: configure kadmin
    command: /bin/bash -c "kadmin.local -q 'addprinc -pw {{ adm_var.password }} {{ adm_var.principal }}@{{ REALM }}'"

  - name: Cloudera Manager Server administrator principal
    command: /bin/bash -c "kadmin.local -q 'addprinc -pw {{ adm_var.password }} cloudera-scm/admin@{{ REALM }}'"

  - name: Cloudera Manager Server administrator keytab
    command: /bin/bash -c "kadmin.local -q 'xst -k /etc/cloudera-scm-server/cmf.keytab cloudera-scm/admin@{{ REALM }}'"

  - name: chown to username you login and chmod as required
    file:
      path: /etc/cloudera-scm-server/cmf.keytab
      owner: "cloudera-scm"
      group: "cloudera-scm"
      mode: 600

  - name: write the kadm5.acl config file
    template:
      src: templates/kadm5.acl.j2
      dest: /var/kerberos/krb5kdc/kadm5.acl

- hosts: workers
  remote_user: root
  vars_files:
    - external_vars.yml    

  tasks:
  - name: Install packages needed for workers
    package:
      name: '{{ item  }}'
      state: present
    with_items:
      - krb5-workstation
      - krb5-libs

  - name: write the krb5 config file
    template:
      src: templates/krb5.conf.j2
      dest: /etc/krb5.conf